version: '3'

services:
  backoffice:
    image: charcochoco/backoffice:1
    build:
      context: ./backoffice  # Mettez le chemin correct vers votre front-end
    ports:
      - "8000:80"  # Port exposé par NGINX dans le conteneur
    environment:
      VITE_API_URL: http://api:8081/api
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-1

  api:
    image: charcochoco/api:1
    build:
      context: ./api  # Mettez le chemin correct vers votre back-end
    ports:
      - "8081:8081"  # Port exposé par votre serveur back-end
    environment:
      MONGO_URL: mongodb://mongodb:27017/ProjetApiRest
    depends_on:
      - mongodb
    networks:
      - network-1

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ProjetApiRest
    volumes:
      - mongodb-data:/data/db
    networks:
      - network-1

networks:
  network-1:
    driver: bridge
 
volumes:
  mongodb-data: